name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        gemfile: [ '7.0.0', '5.1.7' ]
        ruby: [ '3.0', '2.7', '2.6']
        exclude:
          - ruby: '3.0'
            gemfile: '5.1.7'
          - ruby: '2.7'
            gemfile: '5.1.7'
          - ruby: '2.6'
            gemfile: '7.0.0'
      fail-fast: false
    runs-on: ubuntu-20.04
    name: ${{ matrix.ruby }} ${{ matrix.database }} rails-${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update && sudo apt-get install libevent-dev libev-dev python-httplib2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo -E ./ci/run_couchbase.sh
    - run: bundle exec rspec
    env:
      ACTIVE_MODEL_VERSION: ${{ matrix.gemfile }}
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      COUCHBASE_BUCKET: default
      COUCHBASE_USER: tester
      COUCHBASE_PASSWORD: password123
