name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    strategy:
      matrix:
        gemfile: [ '7.0.0', '6.1.3.1', '6.0.3.6', '5.2.5', '5.1.7', '4.2.11.3' ]
        ruby: [ '3.0', '2.7', '2.6', '2.5', '2.4' ]
        exclude:
          - ruby: '3.0'
            gemfile: '5.2.5'
          - ruby: '3.0'
            gemfile: '5.1.7'
          - ruby: '3.0'
            gemfile: '4.2.11.3'
          - ruby: '2.7'
            gemfile: '5.2.5'
          - ruby: '2.7'
            gemfile: '5.1.7'
          - ruby: '2.7'
            gemfile: '4.2.11.3'
          - ruby: '2.6'
            gemfile: '7.0.0'
          - ruby: '2.5'
            gemfile: '7.0.0'
          - ruby: '2.4'
            gemfile: '7.0.0'
          - ruby: '2.4'
            gemfile: '6.1.3.1'
          - ruby: '2.4'
            gemfile: '6.0.3.6'
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }} ${{ matrix.database }} rails-${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec

    env:
      ACTIVE_MODEL_VERSION: ${{ matrix.gemfile }}
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      TRAVIS_CI: true
      RAILS_ENV: test

    services:
